sudo: required

services:
  - docker

script:
  - docker build --build-arg GITHUB_PAT=$GITHUB_PAT -t jasenfinch/hrm-docker .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jasenfinch/hrm-docker
  
notifications:
  email:
    on_success: change
    on_failure: change