name: Docker

on:
  push:
    branches:
      - master

  pull_request:
  
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  
    ubuntu-r:

      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2

        - name: Log into registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
        - name: Build image
          run: docker build . --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} --file ubuntu-r/Dockerfile --tag ubuntu-r

        - name: Push image
          run: |
            IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/ubuntu-r
          
            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            # Set version to current date
            VERSION=${{ steps.date.outputs.date }}
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag ubuntu-r $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
      
    ubuntu-r-xcms:
      needs: ubuntu-r

      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2

        - name: Log into registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
        - name: Build image
          run: docker build . --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} --file ubuntu-r-xcms/Dockerfile --tag ubuntu-r-xcms

        - name: Push image
          run: |
            IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/ubuntu-r-xcms
          
            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            # Set version to current date
            VERSION=${{ steps.date.outputs.date }}
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag ubuntu-r-xcms $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
  
    hrm-docker:
      needs: ubuntu-r-xcms

      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2

        - name: Log into registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
        - name: Build image
          run: docker build . --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} --file hrm-docker/Dockerfile --tag hrm-docker

        - name: Push image
          run: |
            IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/hrm-docker
          
            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            # Set version to current date
            VERSION=${{ steps.date.outputs.date }}
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag hrm-docker $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION